service: chabelita-back-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: umg-chabelita
  region: us-east-1
  memorySize: 1024
  timeout: 30
  environment:
    ENV: ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.ENV}
    NODE_ENV: ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.NODE_ENV}
    DB_HOST: ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DB_HOST}
    DB_DATABASE: ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DB_DATABASE}
    DB_USERNAME: ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DB_USERNAME}
    DB_PASSWORD: ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DB_PASSWORD}
  deploymentBucket:
    name: serverless-deployments-bucket
    serverSideEncryption: AES256
functions:
  get-products:
    handler: src/handlers/products.getProducts
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /product
          method: GET
          cors: true
  get-product-byId:
    handler: src/handlers/products.getProductById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /product/{productId}
          method: GET
          cors: true
  insert-product:
    handler: src/handlers/products.insertProduct
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /product
          method: POST
          cors: true
  update-product:
    handler: src/handlers/products.updateProduct
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /product/{productId}
          method: PUT
          cors: true
  delete-product:
    handler: src/handlers/products.deleteProduct
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /product/{productId}
          method: DELETE
          cors: true                     
  get-order-byId:
    handler: src/handlers/orders.getOrderById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /order/{orderId}
          method: GET
          cors: true
  get-order-byDate:
    handler: src/handlers/orders.getOrderByDate
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /order
          method: GET
          cors: true
  insert-order:
    handler: src/handlers/orders.insertOrder
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /order
          method: POST
          cors: true
  update-order:
    handler: src/handlers/orders.updateOrder
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /order/{orderId}
          method: PUT
          cors: true
  delete-order:
    handler: src/handlers/orders.deleteOrderById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /order/{orderId}
          method: DELETE
          cors: true
  get-detail-order-byId:
    handler: src/handlers/detailorders.getDetailsOrderById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /detailorder/{orderId}
          method: GET
          cors: true
  insert-detail-order:
    handler: src/handlers/detailorders.insertDetailsOrder
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /detailorder
          method: POST
          cors: true
  update-detail-order:
    handler: src/handlers/detailorders.updateDetailsOrder
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /detailorder/{orderId}
          method: PUT
          cors: true
  get-users:
    handler: src/handlers/users.getUser
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /user
          method: GET
          cors: true
  get-user-byId:
    handler: src/handlers/users.getUserById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /user/{userId}
          method: GET
          cors: true
  login-user:
    handler: src/handlers/users.userLogin
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /login
          method: POST
          cors: true
  insert-user:
    handler: src/handlers/users.insertUser
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /user
          method: POST
          cors: true
  update-user:
    handler: src/handlers/users.updateUser
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /user/{userId}
          method: PUT
          cors: true
  delete-user:
    handler: src/handlers/users.deleteUser
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /user/{userId}
          method: DELETE
          cors: true
  get-category:
    handler: src/handlers/category.getCategory
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /category
          method: GET
          cors: true
  get-category-byAdmin:
    handler: src/handlers/category.getCategoryByAdmin
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /categories
          method: GET
          cors: true        
  get-category-byId:
    handler: src/handlers/category.getCategoryById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /category/{categoryId}
          method: GET
          cors: true
  insert-category:
    handler: src/handlers/category.insertCategory
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /category
          method: POST
          cors: true
  update-category:
    handler: src/handlers/category.updateCategory
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /category/{categoryId}
          method: PUT
          cors: true
  delete-category:
    handler: src/handlers/category.deleteCategoryById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /category/{categoryId}
          method: DELETE
          cors: true
  get-seasons:
    handler: src/handlers/seasons.getSeason
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /seasons
          method: GET
          cors: true
  get-seasons-byAdmin:
    handler: src/handlers/seasons.getSeasonByAdmin
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /season
          method: GET
          cors: true        
  get-seasons-byId:
    handler: src/handlers/seasons.getSeasonById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /seasons/{seasonId}
          method: GET
          cors: true
  insert-seasons:
    handler: src/handlers/seasons.insertSeason
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /seasons
          method: POST
          cors: true
  update-seasons:
    handler: src/handlers/seasons.updateSeason
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /seasons/{seasonId}
          method: PUT
          cors: true
  delete-seasons:
    handler: src/handlers/seasons.deleteSeasonById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /seasons/{seasonId}
          method: DELETE
          cors: true
  get-visualizations:
    handler: src/handlers/visualizations.getVisualization
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /visualizations
          method: GET
          cors: true
  get-visualizations-byId:
    handler: src/handlers/visualizations.getVisualizationById
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /visualizations/{visualizationId}
          method: GET
          cors: true
  insert-visualizations:
    handler: src/handlers/visualizations.insertVisualization
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /visualizations
          method: POST
          cors: true
  get-orders:
    handler: src/handlers/orders.getOrder
    layers:
      - ${file(./config.json):${opt:stage, self:provider.stage, 'dev'}.DEPENDENCIES_LAYER}
    events:
      - http:
          path: /orders
          method: GET
          cors: true         
package:
  patterns:
    - '!dependencies_layer/**'
plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-deployment-bucket
custom:
  prune:
    automatic: true
    number: 3